### ISSUE TITLE
1644691589 是什么意思呢？

### ISSUE THREAD

**Issue by kingking888** [MaoningGuan/PyWeChat#6]
请教文件夹名字为1644691589 是什么意思

**Comment by kingking888** [comment]
Launcher.exe 的源码可以分享下吗？

**Comment by MaoningGuan** [comment]
1644691589 随便起的一个文件夹名称，没有什么特别含义，不要随便更改，因为Launcher.exe是把WeChatSpy.dll注入到PC微信，里面设置好了WeChatSpy.dll的路径（路径里面包含了1644691589 这个文件夹）。
Launcher.exe的作用就是把WeChatSpy.dll注入到PC微信客户端，网上应该可以找到对应的源码。

**Comment by kingking888** [comment]
谢谢大佬的耐心回答，感谢

**Comment by kingking888** [comment]
可以加个weixin吗？

**Comment by kingking888** [comment]
大佬，看不懂那几个获取消息的偏移是怎么计算出来的，可以给点提示吗？
